---
# gluster-setup.yml

- hosts: storage
  remote_user: vagrant
  become: yes
  gather_facts: false

  tasks:

  - name: install gluster repo
    package:
      name: centos-release-gluster312.noarch
      state: present

  - name: install gluster software
    package:
      name: glusterfs-server
      state: present

  - name: start glusterd service
    service:
      name: glusterd
      state: started
      enabled: yes


# Gluster Options:
# Distributed Volume: gluster volume create gv0 storage-1:/data/brick1/gv0 storage-2:/data/brick1/gv0
# Replicated Volume: gluster volume create gv0 replica 2 storage-1:/data/brick1/gv0 storage-2:/data/brick1/gv0
# Striped Volume: gluster volume create gv0 stripe 2 storage-1:/data/brick1/gv0 storage-2:/data/brick1/gv0

- hosts: storage-1
  remote_user: vagrant
  become: yes
  gather_facts: false

  tasks:
  - name: create gluster volume
    #command: gluster volume create gv0 storage-1:/data/brick1/gv0 storage-2:/data/brick1/gv0
    gluster_volume:
      state: present
      name: gv0
      bricks: /data/brick1/gv0
      rebalance: yes
      cluster:
        - storage-1
        - storage-2
    run_once: true


#####################
# Client setup
#####################
- hosts: client-1
  remote_user: vagrant
  become: yes
  gather_facts: false

  tasks:

  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - fuse
      - fuse-libs
      - libibverbs
      - centos-release-gluster312.noarch

  - name: install gluster client software
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - glusterfs
      - glusterfs-fuse

  - name: mount gluster volume
    mount:
      path: /mnt
      src: storage-1:/gv0
      fstype: glusterfs
      state: mounted
