# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    #config.vm.define "client-1" do |machine|
    #    machine.vm.hostname = "client-1"
    #    machine.vm.network "private_network", ip: "192.168.33.21"
    #    machine.vm.provision :shell, :path => "bootstrap.sh"
    #    machine.vm.provider "virtualbox" do |vb|
    #        vb.memory = 512
    #        vb.cpus = 1
    #    end
    #end

    (1..3).each do |i|
        config.vm.define "storage-#{i}" do |machine|
            machine.vm.hostname = "storage-#{i}"
            machine.vm.network "private_network", ip: "192.168.33.1#{i}"
            machine.vm.provision :shell, :path => "bootstrap.sh"
            machine.vm.provider "virtualbox" do |vb|
                vb.customize ['createhd', '--filename', "../disks/cephDisk#{i}.vdi", '--size', 100 * 1024]
                vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "../disks/cephDisk#{i}.vdi"]
                vb.memory = 1024
                vb.cpus = 1
            end
        end
    end
end
