# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "centos-bg/7"
    storageDisk01 = './storageDisk01.vdi'
    storageDisk02 = './storageDisk02.vdi'
    storageDisk03 = './storageDisk03.vdi'
    storageDisk04 = './storageDisk04.vdi'
    storageDisk05 = './storageDisk05.vdi'
    storageDisk06 = './storageDisk06.vdi'
    storageDisk07 = './storageDisk07.vdi'
    storageDisk08 = './storageDisk08.vdi'
    storageDisk09 = './storageDisk09.vdi'
    storageDisk10 = './storageDisk10.vdi'
    storageDisk11 = './storageDisk11.vdi'
    storageDisk12 = './storageDisk12.vdi'

    #CONTROLLER = ENV.fetch('CONTROLLER', 'SATA Controller')
    CONTROLLER = 'SCSI'

    config.vm.define "client-1" do |machine|
        machine.vm.hostname = "client-1"
        machine.vm.network "private_network", ip: "192.168.33.21"
        machine.vm.provision :shell, :path => "bootstrap.sh"
        machine.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
        end
    end
    config.vm.define "storage-1" do |machine|
        machine.vm.hostname = "storage-1"
        machine.vm.network "private_network", ip: "192.168.33.11"
        machine.vm.provision :shell, :path => "bootstrap.sh"
        machine.vm.provider "virtualbox" do |vb|
            unless File.exists?(storageDisk01)
                vb.customize ['createhd', '--filename', storageDisk01, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk02)
                vb.customize ['createhd', '--filename', storageDisk02, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk03)
                vb.customize ['createhd', '--filename', storageDisk03, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk04)
                vb.customize ['createhd', '--filename', storageDisk04, '--size', 2 * 1024]
            end
            vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi", "--bootable", "off" ]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 0, '--device', 0, '--type', 'hdd', '--medium', storageDisk01]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storageDisk02]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 2, '--device', 0, '--type', 'hdd', '--medium', storageDisk03]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 3, '--device', 0, '--type', 'hdd', '--medium', storageDisk04]
            vb.memory = 1024
            vb.cpus = 2
        end
    end

    config.vm.define "storage-2" do |machine|
        machine.vm.hostname = "storage-2"
        machine.vm.network "private_network", ip: "192.168.33.12"
        machine.vm.provision :shell, :path => "bootstrap.sh"
        machine.vm.provider "virtualbox" do |vb|
            unless File.exists?(storageDisk05)
                vb.customize ['createhd', '--filename', storageDisk05, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk06)
                vb.customize ['createhd', '--filename', storageDisk06, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk07)
                vb.customize ['createhd', '--filename', storageDisk07, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk08)
                vb.customize ['createhd', '--filename', storageDisk08, '--size', 2 * 1024]
            end
            vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi", "--bootable", "off" ]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 0, '--device', 0, '--type', 'hdd', '--medium', storageDisk05]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storageDisk06]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 2, '--device', 0, '--type', 'hdd', '--medium', storageDisk07]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 3, '--device', 0, '--type', 'hdd', '--medium', storageDisk08]
            vb.memory = 1024
            vb.cpus = 2
        end
    end

    config.vm.define "storage-3" do |machine|
        machine.vm.hostname = "storage-3"
        machine.vm.network "private_network", ip: "192.168.33.13"
        machine.vm.provision :shell, :path => "bootstrap.sh"
        machine.vm.provider "virtualbox" do |vb|
            unless File.exists?(storageDisk09)
                vb.customize ['createhd', '--filename', storageDisk09, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk10)
                vb.customize ['createhd', '--filename', storageDisk10, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk11)
                vb.customize ['createhd', '--filename', storageDisk11, '--size', 2 * 1024]
            end
            unless File.exists?(storageDisk12)
                vb.customize ['createhd', '--filename', storageDisk12, '--size', 2 * 1024]
            end
            vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi", "--bootable", "off" ]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 0, '--device', 0, '--type', 'hdd', '--medium', storageDisk09]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storageDisk10]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 2, '--device', 0, '--type', 'hdd', '--medium', storageDisk11]
            vb.customize ['storageattach', :id, '--storagectl', CONTROLLER, '--port', 3, '--device', 0, '--type', 'hdd', '--medium', storageDisk12]
            vb.memory = 1024
            vb.cpus = 2
        end
    end

end
