# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    storageDisk1 = './storageDisk1.vdi'
    storageDisk2 = './storageDisk2.vdi'

    config.vm.define "client-1" do |machine|
        machine.vm.hostname = "client-1"
        machine.vm.network "private_network", ip: "192.168.33.21"
        machine.vm.provision :shell, :path => "bootstrap-client.sh"
        machine.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
        end
    end
    config.vm.define "storage-1" do |machine|
        machine.vm.hostname = "storage-1"
        machine.vm.network "private_network", ip: "192.168.33.11"
        #machine.vm.provision :shell, :path => "bootstrap-storage.sh"
        machine.vm.provider "virtualbox" do |vb|
            vb.customize ['createhd', '--filename', storageDisk1, '--size', 10 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storageDisk1]
            vb.memory = 1024
            vb.cpus = 1
        end
    end
    config.vm.define "storage-2" do |machine|
        machine.vm.hostname = "storage-1"
        machine.vm.network "private_network", ip: "192.168.33.12"
        machine.vm.provision :shell, :path => "bootstrap-storage.sh"
        machine.vm.provider "virtualbox" do |vb|
            vb.customize ['createhd', '--filename', storageDisk2, '--size', 10 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storageDisk2]
            vb.memory = 1024
            vb.cpus = 1
        end
    end
end
